### ISSUE TITLE
🧱 concrete walls: 3d art assets

### ISSUE THREAD

**Issue by lonnie-ralfs** [benevolent-bees/benevolent.games#10]
- start with the .blend file in this .zip [concrete_barriers.zip](https://github.com/chase-moskal/benevolent.games/files/7920887/concrete_barriers.zip)
- [ ] art must fit within the confines of the base meshes provided in the .blend
- [ ] each collection should contain 1 high poly mesh that was used for baking, and 3 lods, all lods will share the same static from lod1.
    - top quality (this is the source material that is not exported into the game)
    - high quality (this is lod0, it  will be used for the high quality mode and be seen close up. ex. name: `modelname.lod0`)
    - low quality (this is lod1, this is for low quality setting, it will also be used as the static mesh. ex. name:  `modelname.lod1`)
    - bottom quality (this is lod 2, it should be the lowest quality and only be seen at far distances. ex. name: `modelname.lod2`)
- [ ] only 1 full set of pbr textures used across all concrete assets assets at 2k resolution
- [ ] finished work should be in a .blend format

**Comment by Loonietoon** [comment]
![Expanding_T-walls_at_Joint_Security_Station_Loyalty_in_Baghdad,_Iraq_DVIDS173714](https://user-images.githubusercontent.com/19894550/150688952-52ae11db-36d6-414b-bb63-b491e2bf9540.jpg)
![Wave_dissipating_blocks](https://user-images.githubusercontent.com/19894550/150688957-52f382a4-ff64-4f7e-af4c-8d8009460bbd.jpg)
![preview_86](https://user-images.githubusercontent.com/19894550/150688961-6b06ce99-2f16-4409-af0b-24ac6e527f95.jpg)

**Comment by chase-moskal** [comment]
closed due to lack of bandwidth and priority
