### ISSUE TITLE
🚧 hesco barriers: 3d art assets

### ISSUE THREAD

**Issue by lonnie-ralfs** [benevolent-bees/benevolent.games#11]
- start with the .blend file in this .zip [hesco_barriers.zip](https://github.com/chase-moskal/benevolent.games/files/7920909/hesco_barriers.zip)
- [ ] art must fit within the confines of the base meshes provided in the .blend
- [ ] each collection should contain 1 high poly mesh that was used for baking, and 3 lods, all lods will share the same static from lod1.
    - top quality (this is the source material that is not exported into the game)
    - high quality (this is lod0, it  will be used for the high quality mode and be seen close up. ex. name: `modelname.lod0`)
    - low quality (this is lod1, this is for low quality setting, it will also be used as the static mesh. ex. name:  `modelname.lod1`)
    - bottom quality (this is lod 2, it should be the lowest quality and only be seen at far distances. ex. name: `modelname.lod2`)
- [ ] only 1 full set of pbr textures used across all hesco assets at 2k resolution
- [ ] finished work should be in a .blend format

**Comment by Loonietoon** [comment]
![APNAK2SLEJBYXP3JOL3IJB5NOQ](https://user-images.githubusercontent.com/19894550/150689248-f5675065-4e51-4367-ac36-fd093a8ebf8d.jpg)
![blanket-purhchase-agreement-750x375](https://user-images.githubusercontent.com/19894550/150689249-a1ee54fb-1c54-4121-a3a2-2d7e01534f14.jpg)
![1920px-Porta_john_hescos](https://user-images.githubusercontent.com/19894550/150689479-35653e5a-b5e8-4b6f-8527-80a281aecec9.jpg)

**Comment by chase-moskal** [comment]
closed due to lack of bandwidth and priority
