### ISSUE TITLE
🏎️ dunebuggy gameplay

### ISSUE THREAD

**Issue by chase-moskal** [benevolent-bees/benevolent.games#20]
it will be so much fun to be able to drive the dune buggy around!

- [ ] use ammojs vehicle physics to make the dunebuggy drivable
- [ ] should have some squishy suspension
- [ ] we think it would be ideal if the controls were just like vehicles in Halo
- [ ] we'd really like players to be able to jump in and out of the vehicle by pressing the `F` key

------

:moneybag: bitcoin bounty `100k satoshis`  
:money_with_wings: bounty halves every `10 days` after `2022-02-03`

**Comment by chase-moskal** [comment]
some of the relevant files:
- [dunebuggy.ts](https://github.com/chase-moskal/benevolent.games/blob/master/s/game/spawn/dunebuggy.ts)  
    this is the code that spawn the dunebuggy into the map, and where any scripting for the dunebuggy physics and such should belong.
- [player.ts](https://github.com/chase-moskal/benevolent.games/blob/master/s/game/spawn/player.ts)  
    this is the code that spawns the player, and wires up `w-a-s-d` movement and mouselook, and might be a useful reference for how to get mouselook working on the dunebuggy.
- [main-startup-routines.ts line 70](https://github.com/chase-moskal/benevolent.games/blob/2fb0004040ae096f808939f454998416354dec1c/s/startup/main-startup-routines.ts#L70)  
    this line coordinates how the system knows about where the current camera is. that's how the lighting rig (the floating donut) follows the camera's position.

the code for this project has been written very rapidly, to prototype the system -- it isn't clean or well-architected yet -- so feel free to refactor the code and make it better, or also just write the code rapidly and quickly -- because our current focus is to build a prototype quickly, and its okay if it's messy -- because we're planning to have a stabilization and refactoring stage in a month from now, to rewrite and clean everything up into something better organized and architected.

**Comment by chase-moskal** [comment]
we are using the babylon game engine, in combination with `ammo.js` as the physics engine.

in many cases, we can control the physics via babylon `physicsImpostor`s, because babylon has integrated the physics engine.

however for some tasks, we need to circumvent babylon, and directly code against `ammo.js`, which if i remember correctly, can be done by accessing something like `mesh.physicsImpostor.physicsBody` -- which gives us direct access to `ammo.js` physics apis -- we probably need this kind of direct access to implement ammo's vehicle physics.

**Comment by chase-moskal** [comment]
here is `ammo.js`'s vehicle example demo: https://rawcdn.githack.com/kripken/ammo.js/99d0ec0b1e26d7ccc13e013caba8e8a5c98d953b/examples/webgl_demo_vehicle/index.html

and here is the code for that ammojs vehicle demo: https://github.com/kripken/ammo.js/blob/main/examples/webgl_demo_vehicle/index.html#L238

we can probably base our dune buggy physics on this example

**Comment by xxXWarMachineRoXxx** [comment]
sure I'll look into it.

**Comment by chase-moskal** [comment]
shelved due to priority changes
