### ISSUE TITLE
🏃‍♂️ improved player movement

### ISSUE THREAD

**Issue by chase-moskal** [benevolent-bees/benevolent.games#23]
the current player movement could use some improvement.

- the current movement is jumpy, when it hits uneven terrain
- acceleration and deceleration would be an improvement
- perhaps we could customize the "slope-climbing-ability" somehow
- current movement interferes with gravity, which shouldn't happen

------

:moneybag: bitcoin bounty `100k satoshis`  
:money_with_wings: bounty halves every `10 days` after `2022-02-03`

**Comment by GeekOfWires** [comment]
@chase-moskal I'm happy to take a look at updating the player model.

**Comment by chase-moskal** [comment]
@GeekOfWires 🍻👍👍

**Comment by chase-moskal** [comment]
note, we've discovered that the current player movement algorithm interferes with gravity — hopefully improved movement can resolve that issue

**Comment by chase-moskal** [comment]
be advised, major refactors have taken place in `player.ts` as a part of #39

**Comment by chase-moskal** [comment]
closing due to lack of interest, priority, and that much of this work has been done in recent refactors
