### ISSUE TITLE
⚙️ unity integration r&d

### ISSUE THREAD

**Issue by chase-moskal** [benevolent-bees/benevolent.games#36]
we'd like for developers to be able to develop benevolent games in unity.

- we want to pursue a unified api for benevolent games, that can control either babylon or unity
- the goal of this ticket, is to export a unity game, and to control the unity engine via typescript
- we want the unity build to be as optimized and small as possible, ideally, around 5 or 10 megabytes

**Comment by xxXWarMachineRoXxx** [comment]
*Insert Eminem song*

This looks like a job for me 
so everybody just folllow me =>[ na na naana](https://www.youtube.com/watch?v=YVkUvmDQ3HY)

**Comment by chase-moskal** [comment]
shelved due to lack of interest
