### ISSUE TITLE
🔫 gun

### ISSUE THREAD

**Issue by chase-moskal** [benevolent-bees/benevolent.games#8]
we need a gun, ready for gameplay

- [ ] the gun itself
- [ ] hands, to hold the gun in first person
- [ ] animatons
    - idle
    - aim
    - shoot
    - reload
    - rack a round

**Comment by Loonietoon** [comment]
![360_F_54122488_VgOE14olmpIn720EtcHNcVHkud9Kicz4](https://user-images.githubusercontent.com/19894550/150660234-d8a3f74c-04e2-44dc-ad5c-f1b358c98e39.jpg)
![istockphoto-678131264-612x612](https://user-images.githubusercontent.com/19894550/150660236-19d45615-e135-41c0-9330-d0c9cbb03df9.jpg)
![blanket-purhchase-agreement-750x375](https://user-images.githubusercontent.com/19894550/150660241-1835e2fe-84a7-4a21-83dc-b5ef0f2257d9.jpg)

**Comment by chase-moskal** [comment]
closed due to lack of bandwidth and priority
