### ISSUE TITLE
⏳ sandbags walls: 3d art assets

### ISSUE THREAD

**Issue by lonnie-ralfs** [benevolent-bees/benevolent.games#9]
- start with the .blend file in this .zip [sandbags.zip](https://github.com/chase-moskal/benevolent.games/files/7919432/sandbags.zip)
- [ ] art must fit within the confines of the base meshes provided in the .blend
- [ ] each collection should contain 1 high poly mesh that was used for baking, and 3 lods, all lods will share the same static from lod1.
    - top quality (this is the source material that is not exported into the game)
    - high quality (this is lod0, it  will be used for the high quality mode and be seen close up. ex. name: `modelname.lod0`)
    - low quality (this is lod1, this is for low quality setting, it will also be used as the static mesh. ex. name:  `modelname.lod1`)
    - bottom quality (this is lod 2, it should be the lowest quality and only be seen at far distances. ex. name: `modelname.lod2`)
- [ ] only 1 full set of pbr textures used across all sandbag assets at 2k resolution
- [ ] finished work should be in a .blend format

**Comment by Loonietoon** [comment]
![360_F_54122488_VgOE14olmpIn720EtcHNcVHkud9Kicz4](https://user-images.githubusercontent.com/19894550/150660255-a4ff8a6d-977e-4193-95c1-c754cfecc64f.jpg)
![istockphoto-678131264-612x612](https://user-images.githubusercontent.com/19894550/150660257-adcbfb70-cbb1-46fa-8fc2-e1fe043ea9e3.jpg)
![blanket-purhchase-agreement-750x375](https://user-images.githubusercontent.com/19894550/150660258-441ecb54-1ac9-4dec-9f53-3f1b482db9a6.jpg)

**Comment by chase-moskal** [comment]
:call_me_hand::call_me_hand:

might be preferable to use `.` character (rather than `_`) for `modelname.lod0`, `modelname.lod1`, `modelname.lod2`
